### ISSUE TITLE
FR/PR suggestion

### ISSUE THREAD

**Issue by acornforth** [MadMind/StateMachineVisualizationBundle#1]
Hi, I like what you have done with this bundle, I have already found it quite useful, for documenting the changes and overrides made to state-machines in Sylius, which uses the winzou bundle.

I would like to suggest some additions/improvements, but i also notice that there haven't ben any commits to this repo in quite a while. Are you still maintaining this project? If not I would be happy to come on board as a contributor/maintainer to help progress this project. Or I can just fork it and submit a PR with my proposed changes ?

I propose adding a console command that outputs the dotfile to stdout, that way the output can be piped to a dot binary located on another system, (for example if your webserver is running in a docker container where you don't want to install dot), this should also be familiar to those used to working with the symfony workflow component.
We could also add the ability to return the dotfile as a download from the Default Controller

**Comment by MadMind** [comment]
@acornforth I had an idea to add caching of dot representation, so a major refactor is required to split presentation from data layer. Having that, output to console would be easy.
Will do my best in the weekend to start on this and let you know when it's done.

**Comment by acornforth** [comment]
Cool, I have currently hacked this for my local work, i'm just doing a die($result) after the implode on L71. and piping it to dot using curl, it's working for now ;) But certainly moving things out of the controller and into services would be the first thing to do :+1:

**Comment by MadMind** [comment]
@acornforth Could you please check `dev-cache` version and give your feedback.
Added `smv:image` and `smv:dot` export commands.

I think it is time to set minimal required PHP version to 7.3, everything else is EOL already :)

**Comment by acornforth** [comment]
@MadMind of course, happy to give it a try.
had look at the diff already and it's looking good. One suggestion though, how about having the `smv:dot` command print the dotfile contents to stdout? We could keep the existing behaviour when an output filename is provided to the command, but in other cases, it may be useful to use shell pipes `|` and redirects `>` to save/append/pipe directly to dot etc....

usage would look like this:  `php bin/console smv:dot | dot -Tsvg -o graph.svg` or `php bin/console smv:dot > mydotfile.gv`

**Comment by MadMind** [comment]
Released version 0.2.0 that covers these changes
