### ISSUE TITLE
Not working in Symfony 5

### ISSUE THREAD

**Issue by tourze** [MadMind/StateMachineVisualizationBundle#3]
After install, when visit http://127.0.0.1:8000/smv/cms_entity.png, it display:

The controller for URI "/smv/cms_entity.png" is not callable: Controller "StateMachineVisualizationBundle:Default:image" does neither exist as service nor as class.

![image](https://user-images.githubusercontent.com/13899502/128539886-5930a2d5-f45f-4e6e-bb6e-ac7aee794414.png)

Seem that symfony 5 does not support the shortcut in routing.yaml.

**Comment by MadMind** [comment]
Fixed in version 0.3.0
